## Three Tier Achitecture Code Launchin DB , WP and Network from docker-compose

services:
  db: 
    image: mysql:latest
    container_name: mydb1
    networks:
    - chayan-network
    volumnes:
    - /data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=redhat
    - MYSQL_DATABASE=blogdb
    - MYSQL_USER=chayan
    - MYSQL_PASSWORD=redhat

  wp:
    depends_on:
    - db
    image: wordpress:latest
    container_name: mywp1
    networks:
    - chayan-network
    ports:
    - 8080:80


networks:
  chayan-network:
    driver: bridge
